addrecipe/urls.py
from django.urls import path
from . import views

app_name = 'addrecipe'

urlpatterns = [
    path('',views.addrecipe,name="addrecipe"), 

]


favourite/urls.py
from django.urls import path
from .views import favourite_recipes,toggle_favorite

app_name = 'favourite'

urlpatterns = [
    path('favorite/<str:user_name>/', favourite_recipes, name='fav'),
    path('favorite/<str:user_name>/<str:recipe_name>/', toggle_favorite, name='follow'),
]

myprofile/urls.py
from django.urls import path
from . import views

app_name = 'myprofile'

urlpatterns = [
    path('',views.profile,name="myprofile"), 

]


project/urls.py
from django.contrib import admin
from django.urls import path, include
from signin import views as signinviews
from myprofile import views as profile_views
from django.conf.urls.static import static
from django.conf import settings
from recipe.views import *
from addcuisine.views import *
from addoccasion.views import *
from favourite import urls as fav_urls
urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', include('signup.urls', namespace='signup')),
    path('signin/', include('signin.urls', namespace='signin')),
    path('myprofile/', include('myprofile.urls', namespace='myprofile')),
    path('logout/', signinviews.logout_view, name='logout'),
    path('addrecipe/', include('addrecipe.urls', namespace='addrecipe')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
    path('recipe/', include('recipe.urls', namespace='recipe')),
    path('get_recipe_details/', get_recipe_details, name='get_recipe_details'), # return recipe details in json
    path('updaterecipe/', updateRecipe, name='updaterecipe'),
    path('deleterecipe/', deleteRecipe, name='deleterecipe'),
    path('about/', about, name='about'),
    path('dashboard/', dashboard, name='dashboard'),
    
    path('addcuisine/', include('addcuisine.urls', namespace='addcuisine')),
    path('deletecuisine/', deleteCuisine, name='deletecuisine'),
    path('updatecuisine/', updateCuisine, name='updatecuisine'),
    path('cuisines/', cuisines, name='cuisines'),
    
    
    path('addoccasion/', addOccasion, name='addoccasion'),
    path('updateoccasion/', updateOccasion, name='updateoccasion'),
    path('deleteoccasion/', deleteOccasion, name='deleteoccasion'),
    path('occasions/', occasions, name='occasions'),
    path('updatepass/', profile_views.updatepass , name='updatepass'),
    path('', include(fav_urls, namespace='favourite')),  

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('<str:recipe_name>/',views.recipe,name="recipe"), 

]


recipes/urls.py
from django.urls import path
from . import views
app_name = 'recipes'

urlpatterns = [
    path('<str:user_name>',views.recipes,name="recipes"),  
    path('cuisines/<str:cuisine_name>/<str:user_name>/',views.cuisines_recipes,name="cuisine_recipes"),  
    path('occasions/<str:occasion_name>/<str:user_name>/',views.occasion_recipes,name="occasion_recipes"),  

]


signin/urls.py
from django.urls import path
from . import views

app_name = 'signin'

urlpatterns = [
    path('',views.signin,name="signin")
]


signup/urls.py
from django.urls import path
from . import views

app_name = 'signup'  

urlpatterns = [
    path('', views.getpage, name='getpage')
]

favourite/models.py
from django.db import models
from django.contrib.auth import get_user_model
from addrecipe.models import Recipe
User = get_user_model()

class FavoriteRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='recipe')

    class Meta:
        unique_together = ('user', 'recipe')

    def __str__(self):
        return f"{self.user.name}'s favorite recipe: {self.recipe.name}"

signin/models.py
from django.db import models

# Create your models here.

addcuisine/views.py
from django.shortcuts import render

# Create your views here.
import secrets
import string
from django.http import JsonResponse
from .models import Cuisine

def createID(length=32):
    
    alphabet = string.ascii_letters + string.digits
    session_token = ''.join(secrets.choice(alphabet) for _ in range(length))
    return session_token

def addcuisine(request):
    if request.method == 'POST':
        cuisine_name = request.POST.get('name')
        description = request.POST.get('disc')
        image_file = request.FILES.get('image')

        if any([cuisine_name, description, image_file]) is None:
                return JsonResponse({'status_message': "Please fill all required fields!", 'message_class': "error" }, status=400)
        if Cuisine.objects.filter(name=cuisine_name).exists():
                return JsonResponse({'status_message': "Cuisine already exists!", 'message_class': "error" }, status=400)

        token = createID()
        newCuisine = Cuisine.objects.create(
            name=cuisine_name,
            disc=description,
            identifier=token,
            image=image_file
        )
        return JsonResponse({'status_message': "Cuisine Created Successfully", 'message_class': "success"},status=200)

    else :
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic} 
        return render(request, 'addcuisine.html', context)
    
from .models import Cuisine

def cuisines(request):
    all_cuisines = Cuisine.objects.all()
    return render(request, 'cuisines.html',  {'all_cuisines': all_cuisines})

import json
from django.http import JsonResponse

def deleteCuisine(request):
    if request.method == 'POST' :
        data = json.loads(request.body)
        name = data.get('name', '')
        if not name:
            return JsonResponse({'status_message': 'Please Provide a name!','message_class': "error"}, status=400)

        cuisine = Cuisine.objects.filter(name=name).first()
        if not cuisine:
            return JsonResponse({'status_message': 'Cuisine not found!','message_class': "error"}, status=404)

        cuisine.delete()
        return JsonResponse({'status_message': 'Cuisine deleted successfully','message_class': "success"},status=200)
    else : 
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic} 
        return render(request, 'deletecuisine.html', context)

def updateCuisine(request):
    if request.method == 'POST' :
        name = request.POST.get('name')
        description = request.POST.get('disc')
        newname = request.POST.get('newname')
        image_file = request.FILES.get('image')

        if(name is None):
            return JsonResponse({'status_message': "Please Provide a cuisine Name!", 'message_class': "error" }, status=400)
        
        cuisine = Cuisine.objects.filter(name=name).first()
        if not cuisine:
            return JsonResponse({'status_message': 'Cuisine not found.', 'message_class': "error" }, status=404)
        if(newname and Cuisine.objects.filter(name=newname).first()) :
            return JsonResponse({'status_message': 'A Cuisine with the same name already exists!', 'message_class': "error" }, status=400)
        elif(newname) :
            cuisine.name = newname
        
        if(description):
            cuisine.disc = description
        if(image_file):
            cuisine.image = image_file
        
        cuisine.save()
        return JsonResponse({'status_message': 'Cuisine updated successfully', 'message_class': "success" }, status=200)
    else : 
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic}  
        return render(request, 'updatecuisine.html', context)

addoccasion/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
from .models import Occasion
# Create your views here.

import secrets
import string
def createID(length=32):
    alphabet = string.ascii_letters + string.digits
    session_token = ''.join(secrets.choice(alphabet) for _ in range(length))
    return session_token 


def addOccasion(request):
    if request.method == 'POST':
        occassion_name = request.POST.get('name')
        description = request.POST.get('disc')
        image_file = request.FILES.get('image')

        if any([occassion_name, description, image_file]) is None:
                return JsonResponse({'status_message': "Please fill all required fields!", 'message_class': "error" }, status=400)
        if Occasion.objects.filter(name=occassion_name).exists():
                return JsonResponse({'status_message': "Occassion already exists!", 'message_class': "error" }, status=400)

        token = createID()
        newOccassion = Occasion.objects.create(
            name=occassion_name,
            disc=description,
            identifier=token,
            image=image_file
        )
        return JsonResponse({'status_message': "Occassion Created Successfully", 'message_class': "success"},status=200)

    else :
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic} 
        return render(request, 'addoccasion.html', context)


def updateOccasion(request):
    if request.method == 'POST' :
        name = request.POST.get('name')
        description = request.POST.get('disc')
        newname = request.POST.get('newname')
        image_file = request.FILES.get('image')

        if(name is None):
            return JsonResponse({'status_message': "Please Provide an occasion Name!", 'message_class': "error" }, status=400)
        
        occasion = Occasion.objects.filter(name=name).first()
        if not occasion:
            return JsonResponse({'status_message': 'Occasion not found.', 'message_class': "error" }, status=404)
        if(newname and Occasion.objects.filter(name=newname).first()) :
            return JsonResponse({'status_message': 'An Occasion with the same name already exists!', 'message_class': "error" }, status=400)
        elif(newname) :
            occasion.name = newname
        
        if(description):
            occasion.disc = description
        if(image_file):
            occasion.image = image_file
        
        occasion.save()
        return JsonResponse({'status_message': 'Occasion updated successfully', 'message_class': "success" }, status=200)
    else : 
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic}  
        return render(request, 'updateoccasion.html', context)

def deleteOccasion(request):
    if request.method == 'POST' :
        data = json.loads(request.body)
        name = data.get('name', '')
        if not name:
            return JsonResponse({'status_message': 'Please Provide a name!','message_class': "error"}, status=400)

        occasion = Occasion.objects.filter(name=name).first()
        if not occasion:
            return JsonResponse({'status_message': 'Occasion not found!','message_class': "error"}, status=404)

        occasion.delete()
        return JsonResponse({'status_message': 'Occasion deleted successfully','message_class': "success"},status=200)
    else : 
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic} 
        return render(request, 'deleteoccasion.html', context)

def occasions(request):
    all_occasions = Occasion.objects.all()
    return render(request, 'occasions.html',  {'all_occasions': all_occasions})

import json
from django.http import JsonResponse

addrecipe/views.py
from django.shortcuts import render

# Create your views here.

# ID
import secrets
import string
def createID(length=32):
    
    alphabet = string.ascii_letters + string.digits
    session_token = ''.join(secrets.choice(alphabet) for _ in range(length))
    return session_token

import json
from django.http import JsonResponse
from .models import Recipe

def addrecipe(request):
    if request.method == 'POST':
        try:
            recipe_name = request.POST.get('name')
            description = request.POST.get('disc')
            cusine= request.POST.get('cusine')  
            ocasion = request.POST.get('ocasion') 
            ingreds = request.POST.get('ingreds')
            steps = request.POST.get('steps')
            cook_time = request.POST.get('cook_time') 
            prep_time = request.POST.get('prep_time')
            protein = request.POST.get('protein')
            fats = request.POST.get('fats')
            carbs = request.POST.get('carbs')
            image_file = request.FILES.get('image')

            if any([recipe_name, description, cusine, ingreds, steps, cook_time, prep_time, protein, fats, carbs, image_file]) is None:
                return JsonResponse({'status_message': "Please fill all required fields!", 'message_class': "error" }, status=400)



            if Recipe.objects.filter(name=recipe_name).exists():
                return JsonResponse({'status_message': "Recipe already exists!", 'message_class': "error" }, status=400)

            token = createID()
            newRecipe = Recipe.objects.create(
                name=recipe_name,
                disc=description,
                cusine=cusine,
                identifier=token,
                steps=steps,
                ocasion=ocasion,
                ingreds=ingreds,
                cook_time=cook_time,
                prep_time=prep_time,
                protein=float(protein),
                fats=float(fats),
                carbs=float(carbs),
                image=image_file
            )
            return JsonResponse({'status_message': "Recipe Created Successfully", 'message_class': "success"},status=200)
        except Exception as e:
            return JsonResponse({'status_message': str(e), 'message_class': "error"}, status=400)
    
    
    else:    
        name = request.user.name
        user_profile_pic = request.user.profile_image.url if request.user.profile_image else None
        context = {'name':name, 'user_profile_pic': user_profile_pic}
        return render(request, 'addrecipe.html', context)

favourite/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import FavoriteRecipe
from addrecipe.models import Recipe
from signup.models import User
from django.http import HttpResponse
def favourite_recipes(request, user_name):
    user2 = User.objects.filter(name=user_name).first()
    user_favs = FavoriteRecipe.objects.all()
    all_recipes = []
    for favorite in user_favs:
        if favorite.user==user2:
            all_recipes.append(favorite.recipe)
            r =Recipe.objects.filter(name = favorite.recipe.name).first()
            r.isfav = True
    return render(request, 'favourite.html', {'all_recipes': all_recipes})

def toggle_favorite(request, user_name, recipe_name):
    user = User.objects.filter(name=user_name).first()
    recipe = Recipe.objects.filter(name=recipe_name).first()
    favrec = FavoriteRecipe.objects.filter(user=user, recipe=recipe).exists()
    if favrec :
        r =FavoriteRecipe.objects.filter(user=user, recipe=recipe).first()
        r.delete()
    else :
        FavoriteRecipe.objects.create(user=user, recipe=recipe)
    return HttpResponse(status=204)

recipes/views.py
from django.shortcuts import render
from addrecipe.views import Recipe
from favourite.models import FavoriteRecipe
from signup.models import User
# Create your views here.

def recipes(request, user_name):
    all_recipes = Recipe.objects.all()
    user2 = User.objects.filter(name=user_name).first()
    if user_name!='none':
        for r in all_recipes:
            if FavoriteRecipe.objects.filter(recipe=r , user = user2).exists():
                r.isfav= True
    return render(request, 'recipes.html', {'all_recipes': all_recipes})

def cuisines_recipes(request,cuisine_name , user_name):
    all_recipes = Recipe.objects.filter(cusine=cuisine_name)
    user2 = User.objects.filter(name=user_name).first()
    if user_name!='none':
        for r in all_recipes:
            if FavoriteRecipe.objects.filter(recipe=r , user = user2).exists():
                r.isfav= True
    return render(request, 'recipes.html', {'all_recipes': all_recipes})

def occasion_recipes(request,occasion_name , user_name):
    all_recipes = Recipe.objects.filter(ocasion=occasion_name)
    user2 = User.objects.filter(name=user_name).first()
    if user_name!='none':
        for r in all_recipes:
            if FavoriteRecipe.objects.filter(recipe=r , user = user2).exists():
                r.isfav= True
    return render(request, 'recipes.html', {'all_recipes': all_recipes})

templates/Signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign in</title>
    <link rel="stylesheet" href="{% static 'signin/css/style.css' %}">
</head>
<body>

<style> 
    #outter {
        background-image: url( "{% static 'images/signBackground.jpg' %}" );
    }
</style>

    <section>
        <nav>
            <img class="logo" src="{% static 'images/logo.png' %}" alt="" onclick="window.location.href='/'">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'signup:getpage' %}">Sign up</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'recipes:recipes' user.name %}">Recipes</a></li>
                {% else %}
                <li><a href="{% url 'recipes:recipes' user_name='none' %}">Recipes</a></li>
                {% endif %}
                <li><a href="{% url 'cuisines' %}">Cuisines</a></li>
                <li><a href="{% url 'occasions' %}">Occasions</a></li>
            </ul> 
        </nav>

    <div id="outter"> 
    <div class="sign-in-form">
        
        <form method="post" id="loginForm">
            {% csrf_token %}
            {{ form.as_p }} 
            <h1>Sign in</h1>
            <input type="email" placeholder="Email" id="email">
            <div class="input-container"> 
                <input type="password" placeholder="Password" id="password">
                <span class="material-symbols-outlined" id="visibility-toggle">visibility_off</span>
            </div>
            <p id="statusMessage"></p>
            <div class="input button">
                <input type="Submit" value="Login" id="submitButton">
            </div>      
        </form>
        
  
        <hr>
        <p>Don't have an account? <a href="{% url 'signup:getpage' %}"><b>Sign up!</b></a></p>
    </div>
</div>
</section>
</body>

<style>
    .error {
        color: red;
        font-weight: bold;
        margin: 5px 0 5px 0;
    }
    .success {
        color: green;
        font-weight: bold;
        margin-top: 9px;
    }
</style>

<script src="{% static 'signin/js/script.js' %}"></script>
</html>

templates/cuisines.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cuisines</title>
    
    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'cuisines/css/style.css' %}"> 

</head> 
<body>
    <style> 
        .cuisines-header{
            background: url("{% static 'cuisines/images/cuisines.jpg' %}" ) center/cover no-repeat;
        }
    </style>

    <section>
        <nav >
            <img class="logo" src="{% static 'images/logo.png' %}" alt="" onclick="window.location.href='/'">
            <ul id="NAV">                
                <li><a href="{% url 'home' %}">Home</a></li>
                {% if not user.is_authenticated %}
                <li ><a href="{% url 'signup:getpage' %}">Sign up</a></li>
                <li><a href="{% url 'signin:signin' %}">Sign in</a></li>
                {% endif %}
                {% if user.is_superuser %}
                <li ><a href="{% url 'dashboard' %}">Admin Dashboard</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li ><a href="{% url 'myprofile:myprofile' %}">Profile</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'recipes:recipes' user.name %}">Recipes</a></li>
                {% else %}
                <li><a href="{% url 'recipes:recipes' user_name='none' %}">Recipes</a></li>
                {% endif %}

                <li><a href="{% url 'occasions' %}">Occasions</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'favourite:fav' user_name=user.name %}">Favorites</a>
                {% endif %}

                <li><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li style="cursor: pointer;">
                    <a  id="Logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log Out</a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </li>
                {% endif %}
            </ul> 
        </nav>
    </section>
    
     


    <header>

        <div class="container cuisines-header">
            <h1>Cuisines</h1>
        </div>
    
    </header>


    <div class="occasions">
        <div class="container">
            <div class="content">
                {% for cuisine in all_cuisines %}
                <div class="occasion">
                    {% if user.is_authenticated %}
                    <a href="{% url 'recipes:cuisine_recipes' cuisine_name=cuisine.name user_name=user.name %}">

                {% else %}
                    <a href="{% url 'recipes:cuisine_recipes' cuisine_name=cuisine.name user_name='none' %}">Recipes
                {% endif %}
                        <img
                            src="{{ cuisine.image.url }}"
                            alt="{{ cuisine.name }}" 
                        />
                        <h4>{{ cuisine.name }}</h4>
                    </a>
                    <p>{{ cuisine.disc }}</p>
                </div>
                {% endfor %}
            </div>
        </div>


    </div>



    <div class="footer">
        &copy; 2024 <span > WasFit Mama </span> All Rights Reserved
    </div>
    


</body>
</html>

templates/favourite.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <script src="https://kit.fontawesome.com/3929e16ef5.js" crossorigin="anonymous"></script>
    <title>Recipes</title>
</head> 
<body>
    <section>
        <nav>
            <img class="logo" src="{% static 'images/logo.png' %}" alt="" onclick="window.location.href='/'">
            <ul id="NAV">

                <li><a href="{% url 'home' %}">Home</a></li>
                {% if not user.is_authenticated %}
                <li ><a href="{% url 'signup:getpage' %}">Sign up</a></li>
                <li><a href="{% url 'signin:signin' %}">Sign in</a></li>
                {% endif %}
                {% if user.is_superuser %} 
                <li ><a href="{% url 'dashboard' %}">Admin Dashboard</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li ><a href="{% url 'myprofile:myprofile' %}">Profile</a></li>
                {% endif %}
                <li><a href="{% url 'cuisines' %}">Cuisines</a></li>
                <li><a href="{% url 'occasions' %}">Occasions</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'recipes:recipes' user.name %}">Recipes</a></li>
                {% endif %}

                <li><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li style="cursor: pointer;">
                    <a  id="Logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log Out</a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </li>
                {% endif %}


                <li id="SEARCH">
                    <div class="search-box">
                        <input class="search-txt" id="search_item" type="text" name="" placeholder="Recipe Name" onkeyup="Search()">
                        <a class="search-btn" href="#">
                          <i class="fas fa-search"></i>
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
    </section>
    
    <div id="content"> 
        <h2 style="margin:45px 0 25px 0;">Favourite</h2><br>
        
        <div class="all_recipe" id="all_recipe" >
            {% for recipe in all_recipes %}
            
            <div class="card"  recipe_name="{{ recipe.name }}">
                <div class="front">
                    <img src="{{ recipe.image.url }}" id="image" alt="{{ recipe.name }}">
                </div>
                <div class="back">
                    <h3>{{ recipe.name }}</h3>
                    <p>{{ recipe.disc }}</p>
                    <div class="button_">
                        <button class="button-85">
                            <a href="{% url 'recipe:recipe' recipe.name %}">Recipe</a>
                        </button>
                    </div>
                    <div>
                    
                        <a  href="{% url 'favourite:follow' user.name recipe.name %}" type="button" id="favbutton_{{ recipe.name }}">
                            <span class="material-symbols-outlined" style="color: red;" id="favspan_{{ recipe.name }}">favorite</span>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
           
                    
    </div>
            
            
        <br style="background-color: black;">

    
    

    <script src="{% static 'recipes/js/script.js' %}"></script>

    <script>
        document.querySelectorAll('[id^="favbutton_"]').forEach(function(button) {
    button.addEventListener('click', function(event) {
        event.preventDefault(); // Prevent the default action of following the link
        var link = this.href;
        var span = this.querySelector('span');
        
        // Toggle the href attribute
        if (link.includes('follow')) {
            this.href = link.replace('follow', 'unfollow');
        } else {
            this.href = link.replace('unfollow', 'follow');
        }
        
        // Toggle the color of the span
        if (span.style.color === 'red') {
            span.style.color = 'white';
        } else {
            span.style.color = 'red';
        }

        // Manually trigger the link
        window.location.href = this.href;
    });
});

        </script>
    
</body>

</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wasfit Mama</title>
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>
<body>
    <section>
        <nav > 
            <img class="logo" src="{% static 'images/logo.png' %}" alt="">
            <ul id ="NAV">
                {% if not user.is_authenticated %} 
                <li ><a href="{% url 'signup:getpage' %}">Sign up</a></li>
                <li><a href="{% url 'signin:signin' %}">Sign in</a></li>
                {% endif %}
                {% if user.is_superuser %}
                <li ><a href="{% url 'dashboard' %}">Admin Dashboard</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li ><a href="{% url 'myprofile:myprofile' %}">Profile</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li><a href="{% url 'recipes:recipes' user.name %}">Recipes</a></li>
                {% else %}
                <li><a href="{% url 'recipes:recipes' user_name='none' %}">Recipes</a></li>
                {% endif %}
                <li><a href="{% url 'cuisines' %}">Cuisines</a></li>
                <li><a href="{% url 'occasions' %}">Occasions</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'favourite:fav' user_name=user.name %}">Favorites</a>
                {% endif %}

                <li><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li style="cursor: pointer;">
                    <a  id="Logout" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log Out</a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </li>
                {% endif %}


            </ul>
        </nav>
        <div class="main"> 
            <div class="main-text">
                <div class="text1">
                    <div class="text first-text">Welcome to</div>
                    <div class="text sec-text">Wasfit Mama</div>
                </div>
                <h3>Your Destination for Delicious, Nutritious Recipes!</h3>
                {% if user.is_authenticated %}
                    <form action="{% url 'myprofile:myprofile' %}">
                {% else %}
                    <form action="{% url 'signup:getpage' %}">
                {% endif %}
                <button type="submit" id="start">Let's get started</button>
                </form>
            </div>
        </div>
    </section>


  


</body>
</html>